# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
inhibit_all_warnings!
target 'Bohan' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
   use_frameworks!

  # Pods for Bohan

pod 'AFNetworking'
pod 'MJRefresh'
pod 'Masonry', '1.0.2'
pod 'SpinKit'
pod 'IQKeyboardManager'
pod 'YYModel'
pod 'SocketRocket'
pod 'Charts', '3.0.3'
pod 'SAMKeychain'

end
